"""drop question views

Revision ID: 01e732025397
Revises: f1a35a021474
Create Date: 2026-08-03 17:40:03.727392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01e732025397'
down_revision: Union[str, Sequence[str], None] = 'f1a35a021474'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'views')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('views', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
