"""drop question views

Revision ID: 01e732025397
Revises: f1a35a021474
Create Date: 2026-08-03 17:40:03.727392

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '01e732025397'
down_revision: str | Sequence[str] | None = 'f1a35a021474'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'views')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('views', sa.INTEGER(), autoincrement=False, server_default="0", nullable=False))
    # ### end Alembic commands ###
