"""fix vote unique constraint

Revision ID: 2a51bf8fc57f
Revises: cdd4979a8af4
Create Date: 2026-07-31 16:09:59.393418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a51bf8fc57f'
down_revision: Union[str, Sequence[str], None] = 'cdd4979a8af4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('votes_user_id_question_id_answer_id_key'), 'votes', type_='unique')
    op.create_index('ix_vote_user_answer_unique', 'votes', ['user_id', 'answer_id'], unique=True, postgresql_where=sa.text('answer_id IS NOT NULL'))
    op.create_index('ix_vote_user_question_unique', 'votes', ['user_id', 'question_id'], unique=True, postgresql_where=sa.text('question_id IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_vote_user_question_unique', table_name='votes', postgresql_where=sa.text('question_id IS NOT NULL'))
    op.drop_index('ix_vote_user_answer_unique', table_name='votes', postgresql_where=sa.text('answer_id IS NOT NULL'))
    op.create_unique_constraint(op.f('votes_user_id_question_id_answer_id_key'), 'votes', ['user_id', 'question_id', 'answer_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
